### ISSUE TITLE
Without docker

### ISSUE THREAD

**Issue by ugintl** [dougblackjr/devto-scheduler#2]
How to install without docker?

**Comment by dougblackjr** [comment]
@ugintl It is a standard Laravel project (though dated at this point), so you can would follow the steps in the README, minus the docker steps. You would then change the variables inside of your .env to point to your local set up.

This project was created for a contest on dev.to a few years ago, so where the code works, it is definitely a bit dated. Feel free to use it as an example to pull code out of. Closing this issue for now.
